### PR TITLE
use multi-file xml validation

### PR DESCRIPTION
**Pull request by reedstrm**
Take advantage of the the ability to validate more than one file at a time.
Requires https://github.com/Connexions/cnxml/pull/18

### CODE REVIEW

**Comment by reedstrm** [comment]
Once this is merged/tagged, press validation should speed up as well.

**Comment by reedstrm** [comment]
Grr - the travis failure is lint on python 3.4 that I cannot replicate anywhere. Everything passes locally

**Comment by reedstrm** [comment]
Finally found a remnant  python3.4 environment - flake8 there wants the closing bracket not indented at all.
Also hit occasional order of results change.

**Review by Dantemss — APPROVED** [review]
Seems reasonable to me.

**Pull request merged**
